# config/routes.yaml

controllers:
    resource: ../src/Controller/
    type: attribute

# Redirection de la racine vers /home
index_redirect:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: home
